### ISSUE TITLE
KeyError: 'eventKey' while commiting new code

### ISSUE THREAD

**Issue by christiaanvaken** [cvitter/mattermost-bitbucket-bridge#15]
I am running this bridge in a Docker container. When I do a git push with new code, the bridge gives this error:

-----
[2019-04-30 08:45:41,890] ERROR in app: Exception on /hooks/34efcgkkstnmpr7uysth3ce7te [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./bitbucket.py", line 330, in hooks
    response = process_payload_server(hook_path, data)
  File "./bitbucket.py", line 64, in process_payload_server
    event_name = get_event_name(data["eventKey"])
KeyError: 'eventKey'
-----

Any ideas?

**Comment by cvitter** [comment]
Hi @christiaanvaken it looks like the `eventKey` is missing from the payload for some reason. Unfortunately I am unable to troubleshoot further than that right now because I don't have a running Bitbucket or Mattermost server.

Can you provide your version of Bitbucket that you are using in case someone else has ideas?
